//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Admission_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student
    {
        public decimal Student_Id { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Nationality { get; set; }
        public string Country { get; set; }
        public string District { get; set; }
        public string Postal_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Phone_number { get; set; }
        public string Mobile_Number { get; set; }
        public string Email { get; set; }
        public string Province { get; set; }
        public string Photo { get; set; }
        public string CNIC { get; set; }
    }
}
